name: Deploy Static Files to GitHub Pages

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps: 
      - uses: robinraju/release-downloader@v1
        with:
          tag: 'archives'
          fileName: '*.zip'
          out-file-path: 'archives'
      - run:  |
          sudo apt-get install unzip
          unzip "./archives/*.zip" -d ./
          rm -rf archives
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - id: deployment
        uses: actions/deploy-pages@v4

  clean:
    if: always()
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: geekyeggo/delete-artifact@v5.1.0
        if: always()
        with:
          name: github-pages
      - uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          retain_days: 0
          keep_minimum_runs: 0
